using AdrCampus.Application.Identity;
using AdrCampus.Application.Proposals;
using AdrCampus.Core.Domain;
using AdrCampus.Core.Drafts;
using AdrCampus.Core.Proposals;
using AdrCampus.Providers.Drafts.Workbench;
using AethericForge.Runtime.Providers.Staging.InMemory;
namespace AdrCampus.Application.Tests;
public sealed class ProposalApplicationServiceTests
{
    private static readonly OrganizationId Organization = new("aetheric-forge"); private static readonly MemberId Author = new("author-1"); private static readonly DateTimeOffset Now = new(2026, 9, 1, 18, 0, 0, TimeSpan.Zero);
    [Fact] public async Task ActiveAuthorPreparesAndProposesExactDraftVersion() { var (service, repository, draft, _) = await Setup(true); var prepared = await service.PrepareAsync(Organization, Author, draft.Id); var result = await service.ProposeAsync(new(Organization, Author, draft.Id, prepared.Draft!.Version, OperationId.New())); Assert.True(prepared.IsReady); Assert.True(result.IsSuccess); Assert.Null(await repository.GetByAuthorAsync(Organization, Author, draft.Id)); }
    [Fact] public async Task NonMemberCannotPrepareProposeOrRead() { var (service, _, draft, _) = await Setup(false); Assert.False((await service.PrepareAsync(Organization, Author, draft.Id)).IsAuthorized); Assert.Equal(ProposalWriteStatus.UnauthorizedOrNotFound, (await service.ProposeAsync(new(Organization, Author, draft.Id, 1, OperationId.New()))).Status); Assert.False((await service.GetAsync(Organization, Author, draft.Id)).IsAuthorized); }
    [Fact] public async Task MaintainerCanPrepareAndDecideProposal() { var (service, _, draft, authority) = await Setup(true, true); var proposed = await service.ProposeAsync(new(Organization, Author, draft.Id, 1, OperationId.New())); var prepared = await service.PrepareDecisionAsync(Organization, Author, draft.Id, DecisionOutcome.Accepted, ""); var decided = await service.DecideAsync(new(Organization, draft.Id, proposed.Proposal!.ProposedAtUtc, Author, DecisionOutcome.Accepted, prepared.Note!, OperationId.New())); Assert.True(prepared.IsReady); Assert.True(decided.IsSuccess); Assert.Equal(DecisionOutcome.Accepted, decided.Record!.FinalDecision!.Outcome); Assert.True(authority.Maintainer); }
    [Fact] public async Task AuthorityIsRecheckedAtDecisionCommit() { var (service, _, draft, authority) = await Setup(true, true); var proposed = await service.ProposeAsync(new(Organization, Author, draft.Id, 1, OperationId.New())); Assert.True((await service.PrepareDecisionAsync(Organization, Author, draft.Id, DecisionOutcome.Accepted, "")).IsReady); authority.Maintainer = false; var result = await service.DecideAsync(new(Organization, draft.Id, proposed.Proposal!.ProposedAtUtc, Author, DecisionOutcome.Accepted, "", OperationId.New())); Assert.Equal(DecisionWriteStatus.UnauthorizedOrNotFound, result.Status); }
    [Fact] public async Task OrdinaryMemberCannotPrepareOrCommitDecision() { var (service, _, draft, _) = await Setup(true, false); var proposed = await service.ProposeAsync(new(Organization, Author, draft.Id, 1, OperationId.New())); Assert.False((await service.PrepareDecisionAsync(Organization, Author, draft.Id, DecisionOutcome.Accepted, "")).IsAuthorized); Assert.Equal(DecisionWriteStatus.UnauthorizedOrNotFound, (await service.DecideAsync(new(Organization, draft.Id, proposed.Proposal!.ProposedAtUtc, Author, DecisionOutcome.Accepted, "", OperationId.New()))).Status); }
    [Fact] public async Task ReplacementTargetIsShownDuringProposalAndDecisionPreparation() { var repository = new WorkbenchDraftRepository(new InMemoryStagingProvider("workbench")); var targetDraft = AdrDraft.Create(AdrId.New(), Organization, Author, new DraftContent("Existing decision", "Context", "Decision", "Consequences"), Now.AddDays(-2)); await repository.CreateAsync(targetDraft, OperationId.New()); var targetProposal = (await repository.ProposeAsync(Organization, Author, targetDraft.Id, 1, OperationId.New(), Now.AddDays(-1))).Proposal!; await repository.DecideAsync(Organization, targetProposal.Id, targetProposal.ProposedAtUtc, new MemberId("maintainer"), DecisionOutcome.Accepted, "", OperationId.New(), Now); var replacement = AdrDraft.Create(AdrId.New(), Organization, Author, new DraftContent("Replacement decision", "Context", "Decision", "Consequences"), Now, targetDraft.Id); await repository.CreateAsync(replacement, OperationId.New()); var authority = new Authority(true, true); var service = new ProposalApplicationService(repository, repository, repository, authority, new Clock()); var prepared = await service.PrepareAsync(Organization, Author, replacement.Id); var proposed = await service.ProposeAsync(new(Organization, Author, replacement.Id, replacement.Version, OperationId.New())); var decision = await service.PrepareDecisionAsync(Organization, Author, replacement.Id, DecisionOutcome.Accepted, ""); Assert.Equal("Existing decision", prepared.Target!.Title.Value); Assert.Equal(targetDraft.Id, proposed.Proposal!.IntendedSupersessionTargetId); Assert.Equal(targetDraft.Id, decision.Target!.Id); }
    private static async Task<(ProposalApplicationService Service, WorkbenchDraftRepository Repository, AdrDraft Draft, Authority Authority)> Setup(bool member, bool maintainer = false) { var repository = new WorkbenchDraftRepository(new InMemoryStagingProvider("workbench")); var draft = AdrDraft.Create(AdrId.New(), Organization, Author, new DraftContent("Choose PostgreSQL", "Context", "Decision", "Consequences"), Now); await repository.CreateAsync(draft, OperationId.New()); var authority = new Authority(member, maintainer); return (new ProposalApplicationService(repository, repository, repository, authority, new Clock()), repository, draft, authority); }
    private sealed class Authority(bool member, bool maintainer) : IMemberAuthority { public bool Maintainer { get; set; } = maintainer; public Task<bool> IsActiveMemberAsync(OrganizationId organizationId, MemberId memberId, CancellationToken cancellationToken = default) => Task.FromResult(member); public Task<bool> IsActiveMaintainerAsync(OrganizationId organizationId, MemberId memberId, CancellationToken cancellationToken = default) => Task.FromResult(member && Maintainer); }
    private sealed class Clock : TimeProvider { public override DateTimeOffset GetUtcNow() => Now.AddMinutes(1); }
}
